#!/bin/bash
/app/dockcheck.sh -n | sed -r "s:\x1B\[[0-9;]*[mK]::g" > /app/containers_temp
cat /app/containers_temp > /app/containers
echo "$(date). Cron ran without error." >> /var/log/cron.log

DISCORD_FILE=/app/DISCORD_NOTIFY
if [ -f "$DISCORD_FILE" ]; then
DISCORD_URL=$(</app/DISCORD_NOTIFY)
grep -oPz '(?<=Containers with updates available:\n)(?s).*(?=\n\n)' /app/containers > /app/notifymsg 
        notifymsg=/app/notifymsg
        if [ -f "$notifymsg" ]; then

                sed -i '1i There is updates available' /app/notifymsg
                cat /app/notifymsg | apprise $DISCORD_URL
                rm /app/notifymsg
                echo "1" > /app/notifysent
        else
        echo "0" /app/notifysent
        fi

fi