#!/bin/bash
/app/dockcheck.sh -n | sed -r "s:\x1B\[[0-9;]*[mK]::g" > /app/containers_temp
cat /app/containers_temp > /app/containers
echo "$(date). Cron ran without error." >> /var/log/cron.log

DISCORD_FILE=/app/DISCORD_NOTIFY
if [ -f "$DISCORD_FILE" ]; then
DISCORD_URL=$(</app/DISCORD_NOTIFY)
grep -oPz '(?<=Containers with updates available:\n)(?s).*(?=\n\n)' /app/containers > /app/notifymsg 
        notifymsg=/app/notifymsg
        if [ ! -s "$notifymsg" ]; then

                sed -i '1i There is updates available' /app/notifymsg
                cat /app/notifymsg | apprise $DISCORD_URL
                rm /app/notifymsg
                

        fi

fi

MAIL_FILE=/app/MAIL_NOTIFY
if [ -f "$MAIL_FILE" ]; then
MAIL_URL=$(</app/MAIL_NOTIFY)
grep -oPz '(?<=Containers with updates available:\n)(?s).*(?=\n\n)' /app/containers > /app/notifymsg 
        notifymsg=/app/notifymsg
        if [ ! -s "$notifymsg" ]; then

                sed -i '1i There is updates available' /app/notifymsg
                cat /app/notifymsg | apprise $MAIL_URL
                rm /app/notifymsg
                

        fi

fi

TELEGRAM_FILE=/app/TELEGRAM_NOTIFY
if [ -f "$TELEGRAM_FILE" ]; then
TELEGRAM_URL=$(</app/TELEGRAM_NOTIFY)
grep -oPz '(?<=Containers with updates available:\n)(?s).*(?=\n\n)' /app/containers > /app/notifymsg 
        notifymsg=/app/notifymsg
        if [ ! -s "$notifymsg" ]; then

                sed -i '1i There is updates available' /app/notifymsg
                cat /app/notifymsg | apprise $TELEGRAM_URL
                rm /app/notifymsg
                

        fi

fi