#!/bin/bash
/app/dockcheck.sh -n | sed -r "s:\x1B\[[0-9;]*[mK]::g" > /app/containers_temp
cat /app/containers_temp > /app/containers
echo "$(date). Cron ran without error." >> /var/log/cron.log



NOTIFY_URLS=/app/NOTIFY_URLS
if [ -f "$NOTIFY_URLS" ]; then
        NOTIFY_URLS=$(</app/NOTIFY_URLS)
        grep -oPz '(?<=Containers with updates available:\n)(?s).*(?=\n\n)' /app/containers > /app/notifymsg 
        notifymsg=/app/notifymsg
        
        if [ -s "$notifymsg" ]; then
                
                NOTIFY_DEBUG=/app/NOTIFY_DEBUG
                if [ -f "$NOTIFY_DEBUG" ]; then

                        sed -i '1i There is updates available for:' /app/notifymsg
                        notifymsg="$(cat /app/notifymsg | tr -d '\0')"
                        
                        apprise -vvvv -t "Dockcheck-web Notify" -b "$notifymsg" "$NOTIFY_URLS"
                        rm /app/notifymsg
                

                else

                        sed -i '1i There is updates available for:' /app/notifymsg
                        notifymsg="$(cat /app/notifymsg | tr -d '\0')"
                        apprise -t "Dockcheck-web Notify" -b "$notifymsg" "$NOTIFY_URLS"
                        rm /app/notifymsg
                fi
        fi
fi

