#!/bin/bash
#POSTGRESQL INSTALL

mkdir /run/postgresql
adduser postgres -G postgres -H -s /bin/bash -D 
chown postgres:postgres /run/postgresql/

mkdir /var/lib/postgresql/data
chmod 0700 /var/lib/postgresql/data
chown -R postgres:postgres /var/lib/postgresql
su postgres -c "initdb -D /var/lib/postgresql/data"
#cp /app/postgresql.conf /var/lib/postgresql/data/postgresql.conf
echo "host all all 0.0.0.0/0 md5" >> /var/lib/postgresql/data/pg_hba.conf
echo "listen_addresses='*'" >> /var/lib/postgresql/data/postgresql.conf
chown -R postgres:postgres /var/lib/postgresql
su postgres -c "pg_ctl start -D /var/lib/postgresql/data"
su postgres -c psql